services:
  auth_db:
    image: postgres:latest
    container_name: db_auth_service
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chat_db:
    image: postgres:latest
    container_name: db_chat_service
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/chat_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis_db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
    volumes:
      - ./volumes/redis_data:/var/lib/redis/data\
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - ./volumes/rabbitmq_data:/var/lib/rabbitmq

  auth_service:
    build:
      context: auth_service
    container_name: auth_service
    command: /app/auth_start.sh
    volumes:
      - ./auth_service:/app
    depends_on:
      - auth_db
      - rabbitmq
    ports:
      - "8000:8000"

volumes:
  auth_db_data:
  chat_db_data:
  rabbitmq_data:
