services:
  auth-db:
    image: postgres:latest
    container_name: auth-service
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../volumes/auth-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chat-db:
    image: postgres:latest
    container_name: chat-service
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../volumes/chat-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis_db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
    volumes:
      - ../volumes/redis_data:/var/lib/redis/data\
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: ../auth-service
    volumes:
      - ../auth-service:/app
    depends_on:
      - auth-db
    ports:
      - "8000:8000"

volumes:
  auth-db-data:
  chat-db-data:
