services:
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chat-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  auth-service:
    build:
      context: ../auth-service
    volumes:
      - ../auth-service:/app
    depends_on:
      - auth-db
    ports:
      - "8000:8000"

volumes:
  auth-db-data:
  chat-db-data:
