on:
  push:
    branches: [ "setup_github_actions" ]
  pull_request:
    branches: [ "setup_github_actions" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
        
    steps:
    # Step 1: Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install python 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-asyncio
        pip install pytest-dotenv
        
    # Step 4: Build Docker images for the applications
    - name: Build docker containers
      run: docker compose build

    # Step 5: Start the docker containers
    - name: Run docker containers
      run: docker compose up -d

    # Step 6: Run auth_service test
    - name: Run authservice tests
      run: |
        cd auth_service
        pytest 

    # Step 7: Tear down services
    - name: Tear down Docker containers
      run: docker compose down 
